### PR TITLE
Fix a `self.options.remove()` false positive

### PR DESCRIPTION
**Pull request by valgur**
Triggered in https://github.com/conan-io/conan-center-index/pull/19381#issuecomment-1691437774 for `self.options.remove_deprecations`.

### CODE REVIEW

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by valgur** [comment]
Could someone hit "merge" as well, please? :smile:

**Comment by uilianries** [comment]
@valgur Need to fix tests first. It seems be a networking error, I'll take a look.

**Comment by uilianries** [comment]
I gonna merge it manually. After checking logs, it's related to PyYAML

**Comment by uilianries** [comment]
@valgur There is a hotfix available in master branch. Could you please rebase your branch, so it should work now.

**Comment by valgur** [comment]
@uilianries Done. The checks are green now.

**Pull request merged**
