### PR TITLE
conan-center: add meson to exception list of KB-H019 (it contains a cmake script)

### PR DESCRIPTION
**Pull request by madebr**
This pr adds meson to the exception list of KB-H019.

This *should* fix the CI failures I'm having with pkgconf at https://github.com/conan-io/conan-center-index/pull/1013#issuecomment-653746667

I've just checked meson 0.54.3 and it contains the following cmake script:
- **bin/mesonbuild/cmake/data/preload.cmake**

I've copied the contents of the script here below.
I think an exception is required instead of adding it to `cpp_info.builddirs`.

<details>

<summary>contents of meson's preload.cmake</summary>

```cmake
if(MESON_PS_LOADED)
  return()
endif()

set(MESON_PS_LOADED ON)

# Dummy macros that have a special meaning in the meson code
macro(meson_ps_execute_delayed_calls)
endmacro()

macro(meson_ps_reload_vars)
endmacro()

# Helper macro to inspect the current CMake state
macro(meson_ps_inspect_vars)
  set(MESON_PS_CMAKE_CURRENT_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
  set(MESON_PS_CMAKE_CURRENT_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  meson_ps_execute_delayed_calls()
endmacro()


# Override some system functions with custom code and forward the args
# to the original function
macro(add_custom_command)
  meson_ps_inspect_vars()
  _add_custom_command(${ARGV})
endmacro()

macro(add_custom_target)
  meson_ps_inspect_vars()
  _add_custom_target(${ARGV})
endmacro()

macro(set_property)
  meson_ps_inspect_vars()
  _set_property(${ARGV})
endmacro()

function(set_source_files_properties)
  set(FILES)
  set(I 0)
  set(PROPERTIES OFF)

  while(I LESS ARGC)
    if(NOT PROPERTIES)
      if("${ARGV${I}}" STREQUAL "PROPERTIES")
        set(PROPERTIES ON)
      else()
        list(APPEND FILES "${ARGV${I}}")
      endif()

      math(EXPR I "${I} + 1")
    else()
      set(ID_IDX ${I})
      math(EXPR PROP_IDX "${ID_IDX} + 1")

      set(ID   "${ARGV${ID_IDX}}")
      set(PROP "${ARGV${PROP_IDX}}")

      set_property(SOURCE ${FILES} PROPERTY "${ID}" "${PROP}")
      math(EXPR I "${I} + 2")
    endif()
  endwhile()
endfunction()

set(MESON_PS_DELAYED_CALLS add_custom_command;add_custom_target;set_property)
meson_ps_reload_vars()
```

</details>

/cc @uilianries @ericLemanissier

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Just To be clear, the pkgconf fails independantly of this hook:
```
ERROR: pkgconf/1.7.3 (test package): Error in test() method, line 34 	raise ConanException("PKG_CONFIG variable incorrect") 	ConanException: PKG_CONFIG variable incorrect
```

**Comment by madebr** [comment]
Indeed, the pkgconf recipe isn't finished yet.
The error/warning when running ninja install on windows is non-fatal btw.

**Comment by SpaceIm** [comment]
I've added this folder to builddirs https://github.com/conan-io/conan-center-index/pull/4420, it's a recurrent source of misleading errors reports in PRs, and it pollutes logs for consumers.

**Comment by SpaceIm** [comment]
Oh I see, this PR is still opened 😢

**Comment by ericLemanissier** [comment]
this may not be needed any more, now that https://github.com/conan-io/conan-center-index/pull/4420 is merged

**Comment by danimtb** [comment]
I think this PR needs to be updated with latest changes in master branch to make the CI green

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@madebr this PR can be closed, with https://github.com/conan-io/conan-center-index/pull/4420 merged

**Comment by madebr** [comment]
Closed it is then!

**Pull request closed without merging**
