### PR TITLE
#100 do not allow system requirements

### LINKED ISSUE #100: [conan center] check there is no system_requirements
I think we have previously agreed to disallow `system_requirements` in conan-center-index
so, it would be nice to check in hook there are no `system_requirements` methods
all exceptions will be white-listed in hook I guess

### PR DESCRIPTION
**Pull request by uilianries**
As discussed before, `system_requirements` is evil and should be avoided. This hook looks its declaration in the conanfile.

closes #100 

Wiki:

#### **<a name="KB-H032">#KB-H032</a>: "SYSTEM REQUIREMENTS"**

System requires can be used as an option when a Conan package is not available the same package can be installer system package manager. However, it can cause  reproducibility problems, since the package may vary according the distribution or OS. Conan is not able to track its metadata, so that, installing system packages by recipe is not allowed.

### CODE REVIEW

**Comment by memsharded** [comment]
Just be aware that there might be a couple of them like OpenCV that would be extremely challenging to get Gtk-dev components in the system correctly. 
Maybe we should block just the install, but not the check of system dependencies.

**Comment by uilianries** [comment]
> Just be aware that there might be a couple of them like OpenCV that would be extremely challenging to get Gtk-dev components in the system correctly.
> Maybe we should block just the install, but not the check of system dependencies.

I see. So should we add a whitelist, e.g OpenCV

**Comment by memsharded** [comment]
No, the OpenCV recipe must check that those system packages are installed or fail otherwise listing the packages to install. Do not allow to install system packages by recipes, but check them.

**Comment by uilianries** [comment]
understood, thanks for clarifying

**Comment by uilianries** [comment]
All conflicts has been solved.

**Comment by SSE4** [comment]
@uilianries conflicts again

**Comment by uilianries** [comment]
All conflicts has been solved. (2)

**Comment by Croydon** [comment]
Could we move this one forward?

**Comment by danimtb** [comment]
I think we should be prepared to whitelist some of the packages as we are planning to introduce some system requirements as "proxy recipes". @uilianries could you please include that in this PR and whitelist `libusb` at the moment? Thanks!!

**Comment by uilianries** [comment]
@danimtb Done, libusb is part of allowlist now.

**Pull request merged**
