### PR TITLE
Relax immutable source hook

### PR DESCRIPTION
**Pull request by uilianries**
/cc @danimtb

### CODE REVIEW

**Comment by uilianries** [comment]
Travis is failing, but is related to OpenSSL  install

**Comment by danimtb** [comment]
Yes, don't worry about the Mac Py2.7 CI

**Comment by uilianries** [comment]
I need to improve these tests. There is no test checking an invalid case.

**Comment by uilianries** [comment]
Forget about, the tests/test_hooks/conan-center/test_conandata.py contains all test needed.

**Pull request merged**
