### PR TITLE
#188 Check for cmake_verbose_makefile

### LINKED ISSUE #188: [conan center] check CMAKE_VERBOSE_MAKEFILE
from https://github.com/conan-io/conan-center-index/pull/1485/files#r416636412
some recipes are using `CMAKE_VERBOSE_MAKEFILE` in their **CMakeLists.txt** or **test_package/CMakeLists.txt**.
/cc @uilianries

### PR DESCRIPTION
**Pull request by uilianries**
- Cmake verbose makefile definition should not be used.

closes #188 

Wiki:

#### **<a name="KB-H046">#KB-H046</a>: "CMAKE VERBOSE MAKEFILE"**

The CMake definition CMAKE_VERBOSE_MAKEFILE helps for debugging when developing, however, for regular CI build, it increases the log size and it's only required when problem occur and need to be verified.

### CODE REVIEW

**Comment by danimtb** [comment]
conflicts!

**Comment by uilianries** [comment]
@danimtb All fixed!

**Comment by SSE4** [comment]
conflicts again! @uilianries

**Comment by uilianries** [comment]
@SSE4 Fixed!

**Comment by danimtb** [comment]
Added to the wiki https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h046-cmake-verbose-makefile

**Comment by uilianries** [comment]
Thank you @danimtb !

**Pull request merged**
