### PR TITLE
Add Conan hooks logo

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This is a possible logo for Conan hooks.

Regards!

### CODE REVIEW

**Comment by danimtb** [comment]
image

I am not sure about the logo LOL
We will need the opinion of @conan-io/barbarians here

**Comment by lasote** [comment]
LoL, so, the hooks will kill Conan?

**Comment by uilianries** [comment]
@lasote it's a bait for C++ users :joy: 


BTW I found some similar images for "Git Hooks":









Since @lasote is a pirate/seaman/captain, we could change his icon, putting a hook on his hand :joy:

**Comment by lasote** [comment]
LoL. The difference with yours is that the hole in these pictures was already there, so no pain for the tools.

**Comment by danimtb** [comment]
I really like the crane hook though. It would fit the concept of "building" apps with Conan cubes (packages)

**Comment by uilianries** [comment]
@danimtb I gonna update to use the crane. It sounds better, since Conan uses "blocks".

**Comment by danimtb** [comment]
@uilianries did you do a new design with the crane? It could be cool

**Comment by uilianries** [comment]
@danimtb @lasote 

conan_crane_hook_3
conan_crane_hook_2
conan_crane_hook

**Comment by lasote** [comment]
Maybe the last one. By the way, I love to be on the crane hahaha but better not.

**Comment by danimtb** [comment]
yes, I also like the last one although the first one kept me laughing for some minutes 🤣

**Comment by uilianries** [comment]
I loved the first one haha! I need to retouch the last one, it has some background that I need to remove.

**Comment by uilianries** [comment]
Here are 3 new versions based on the last choice:

conan-hook-3


conan-hook-2



conan-hook-1

**Comment by danimtb** [comment]
First one is my choice!!

**Comment by lasote** [comment]
First

**Comment by uilianries** [comment]
first

**Pull request merged**
