### PR TITLE
[conan-center] KB-H069 default_options is not allow on test_package

### LINKED ISSUE #287: Avoid usage of 'default_options' in test-package
Seen here: https://github.com/conan-io/conan-center-index/pull/5024

If using `default_options` in `test_package/conanfile.py` it is very likely that the computed package-id won't exist (we only build packages with the default value for options). It would be nice to prevent these tests to modify the default options. Not sure if there is a hook right now that can do the work, maybe we need to introduce it in Conan first.

### PR DESCRIPTION
**Pull request by uilianries**
Test package should not use default options, otherwise, it won't test the default package configuration.

closes #287

Wiki: 

#### **<a name="KB-H069">#KB-H069</a>: "TEST PACKAGE - NO DEFAULT OPTIONS"**

When testing the built package, we need to validate the default configuration, including its options. in case of use
custom options via `default_options`, this will not guarantee the default package state.

### CODE REVIEW

**Review by SSE4 — DISMISSED** [review]
I think it's reasonable. are there valid use-cases? maybe changing some options for other requirements/build_requirements (not a package under the test)

**Comment by uilianries** [comment]
> I think it's reasonable. are there valid use-cases? maybe changing some options for other requirements/build_requirements (not a package under the test)

Maybe shared option for requires/build_requires only. Otherwise, we would not have that configuration available on Conan Center.
But still, if you need to enforce shared, you should do it on the recipe, not on the test package

**Comment by uilianries** [comment]
Done

**Comment by SSE4** [comment]
> Details

now it fails :(

**Comment by SSE4** [comment]
also, job wasn't able to report into this issue, but here is the output (part of it):
```
FAIL: conan export recipes/backward-cpp/all/conanfile.py backward-cpp/1.6@
FAIL: conan export recipes/backward-cpp/all/conanfile.py backward-cpp/1.5@
FAIL: conan export recipes/backward-cpp/all/conanfile.py backward-cpp/1.4@
FAIL: conan export recipes/gettext/all/conanfile.py gettext/0.21@
FAIL: conan export recipes/gettext/all/conanfile.py gettext/0.20.1@
```

**Comment by uilianries** [comment]
I'll investigate. Thank you @SSE4 for pinging!

**Comment by uilianries** [comment]
@SSE4 The new conan pylint does not like `conans` as import. I just updated to `conan`. Unfortunately, `python_requires`is not ported to `conan` yet.

**Comment by SSE4** [comment]
> @SSE4 The new conan pylint does not like `conans` as import. I just updated to `conan`. Unfortunately, `python_requires`is not ported to `conan` yet.

what about `python_requires`? where is it used and for what and why?

**Comment by uilianries** [comment]
> what about python_requires? where is it used and for what and why?

For testing in that case. As it requires the pip package python_version, it validates a possible import error.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
