### PR TITLE
Check option for deletion

### LINKED ISSUE #179: [conan center] prefer del self.options rather self.options.remove
from https://github.com/conan-io/conan-center-index/pull/1375/files#r409740204
/cc @uilianries 
prefer this syntax:
```
del self.options.darwin_ssl
```
over
```
self.options.remove("darwin_ssl")
```

### PR DESCRIPTION
**Pull request by uilianries**
closes #179

/cc @SSE4 @danimtb 

#### **<a name="KB-H045">#KB-H045</a>: "DELETE OPTIONS"**

The method `self.options.remove` was introduced in Conan 0.x, however Conan 1.x brings a more pythonic way for removing options from your recipe.

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries I have been thinking about it a lil bit.
with syntax:
```
self.options.remove("shared")
```
it's easy to make typo, e.g.:
```
self.options.remove("shated")
```
while with:
```
del self.options.shared
```
it's much better (at least IntelliSense/editor helps here)

**Comment by uilianries** [comment]
Good catch! I didn't think about the typo case, but it makes total sense as we had real cases in Conan Center Index.

**Comment by danimtb** [comment]
updated wiki

**Comment by uilianries** [comment]
Thanks a lot @danimtb !

**Pull request merged**
