### PR TITLE
allow no sha256 of googlesource.com

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes conan-io/hooks#414

### CODE REVIEW

**Comment by ericLemanissier** [comment]
`+ python -m pip install --upgrade pip` ends with `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/var/folders/c2/vd5y5mfs33q84hyzmxvqmyjm0000gp/T/py39/lib/python3.9/site-packages/platformdirs-2.5.2.dist-info/METADATA'`
wat ?
could it be linked to this change https://github.com/conan-io/hooks/commit/da35c8c691e27eba7d9893a3eea0f40af3575715#diff-fc2c51474f3f0925deb915167cd2fa8fd8017243ae6bf60484b851e3920fae81 @uilianries ?

**Comment by uilianries** [comment]
@ericLemanissier Nope, that change was exactly to fix it on Mac. I had the same problem last week, and for some reason, it worked on that PR. I'm testing Python 3.8 right now, if it works, we should switch from 3.9 to 3.8. It could 3.10 too, but we don't have it installed in our Mac machines yet.

**Review by uilianries — DISMISSED** [review]
LGTM

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
Thanks @ericLemanissier !

**Pull request merged**
