### PR TITLE
[conan center] allow different sources per config

### PR DESCRIPTION
**Pull request by SSE4**
closes: #259

### CODE REVIEW

**Review by danimtb — APPROVED** [review]

**Comment by SSE4** [comment]
@uilianries any idea why does it fail? unfortunately, astroid doesn't install on my system:
```
  ERROR: Command errored out with exit status 1:
   command: /Users/sse4/.pyenv/versions/3.8.0/bin/python /Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/vq/v4_w2g4j5k1170y70pgfktzr0000gn/T/pip-build-env-jfgpq_0r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1'
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sse4/.pyenv/versions/3.8.0/bin/python /Users/sse4/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/vq/v4_w2g4j5k1170y70pgfktzr0000gn/T/pip-build-env-jfgpq_0r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1' Check the logs for full command output.
WARNING: You are using pip version 20.1; however, version 21.0 is available.
You should consider upgrading via the '/Users/sse4/.pyenv/versions/3.8.0/bin/python -m pip install --upgrade pip' command.
```

**Comment by uilianries** [comment]
I'll run on Linux and Mac.

**Comment by uilianries** [comment]
Something introduced on Conan 1.33.0 changed its behavior.

I can reproduce the same error when running on Linux, with Conan 1.34.0-dev and 1.33.0

```
$ conan --version
Conan version 1.32.1
$ pytest -v tests/test_hooks/test_recipe_linter.py 
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.8.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/uilian/Development/conan/hooks/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/uilian/Development/conan/hooks
collected 9 items                                                                                                                                                                                                                           

tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_basic_0 PASSED                                                                                                                                                        [ 11%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_basic_1 PASSED                                                                                                                                                        [ 22%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_catch_them_all PASSED                                                                                                                                                 [ 33%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_conan_data PASSED                                                                                                                                                     [ 44%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_custom_plugin PASSED                                                                                                                                                  [ 55%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_custom_rcfile PASSED                                                                                                                                                  [ 66%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_dynamic_fields PASSED                                                                                                                                                 [ 77%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_path_with_spaces PASSED                                                                                                                                               [ 88%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_python_requires PASSED                                                                                                                                                [100%]
```

```
$ conan --version
Conan version 1.33.0
$ pytest -v tests/test_hooks/test_recipe_linter.py 
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.8.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/uilian/Development/conan/hooks/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/uilian/Development/conan/hooks
collected 9 items                                                                                                                                                                                                                           

tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_basic_0 PASSED                                                                                                                                                        [ 11%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_basic_1 PASSED                                                                                                                                                        [ 22%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_catch_them_all PASSED                                                                                                                                                 [ 33%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_conan_data PASSED                                                                                                                                                     [ 44%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_custom_plugin FAILED                                                                                                                                                  [ 55%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_custom_rcfile PASSED                                                                                                                                                  [ 66%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_dynamic_fields PASSED                                                                                                                                                 [ 77%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_path_with_spaces PASSED                                                                                                                                               [ 88%]
tests/test_hooks/test_recipe_linter.py::RecipeLinterTests::test_python_requires PASSED                                                                                                                                                [100%]
```

We have to investigate what affected export command behavior.

**Comment by SSE4** [comment]
@uilianries @jgsogo ready!

**Review by jgsogo — APPROVED** [review]
👍

**Comment by jgsogo** [comment]
Running the job to check all recipes, just in case this breaks something we didn't notice: https://ci-conan-prod.jfrog.team/job/ScheduledExportCheck/523/

**Pull request merged**
