### PR TITLE
CRLF - Turn into a warning

### PR DESCRIPTION
**Pull request by jgsogo**
I feel like this is not working as expected: https://github.com/conan-io/conan-center-index/pull/6133

Until we have a better understanding of what is going on and why these PRs are failing, this cannot block PRs.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
The hook is working as expected. I have just force-pushed, overriding my initial commit.

**Comment by jgsogo** [comment]
We are running some tests on a private repo we have before deploying changes to the library and it is failing for some recipes (`fmt` and `nlopt`). We are afraid that when the repository is cloned in Windows some files will use CRLF locally... or after copying files to the Conan cache in a Windows machine.

Then we saw your PR failing and we thought it could be something _generalized_. Sure we need to wait for your PR.

**Review by danimtb — APPROVED** [review]

**Comment by uilianries** [comment]
Have to update the tests. They expect WARN message, not ERROR.

**Comment by jgsogo** [comment]
There are other PRs that are building in windows right now and they are not failing with this error. Not sure if this is something that has just happened to you, @danimtb

**Comment by jgsogo** [comment]
Ok, I'm now understanding all of this better. The hook is checking many more files than the ones we are enforcing in `.gitattributes` so it is possible that there are existing files with CRLF and the hook will complain. This can be inconvenient if the user doesn't know how to change the line endings...

**Comment by uilianries** [comment]
@jgsogo Could we update the hook message with a command hint? Or maybe Use KB error in CCI page

**Comment by jgsogo** [comment]
Hi! In the end, it looks like the error was on one of the Windows machines that was configured with `core.autocrlf=true` (Git configuration), it was converting line-endings and the hook was triggering the error 😌

**Pull request closed without merging**
