### PR TITLE
Add python_requires_extend to members_typo_checker

### LINKED ISSUE #189: [bug] members_typo_checker reporting python_requires_extend as typo
```
[HOOK - members_typo_checker.py] pre_export(): WARN: The 'python_requires_extend' member looks like a typo. Similar to:
[HOOK - members_typo_checker.py] pre_export(): WARN:     python_requires
```

### PR DESCRIPTION
**Pull request by cguldner**
Fixes #189

### CODE REVIEW

**Comment by cguldner** [comment]
@uilianries This should be good to go

**Review by danimtb — APPROVED** [review]

**Comment by cguldner** [comment]
@uilianries Can you merge this when you get a chance?

**Comment by cguldner** [comment]
@uilianries Can you merge this one line change?

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@cguldner Sorry my delay. I have no power to merge, but it looks good.

@danimtb @jgsogo Could you review and merge if okay?

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
